### ISSUE TITLE
Image Verbalization for Expansion

### ISSUE THREAD

**Issue by kiucho** [OpenMatch/UniVL-DR#1]
Hello, I'm a student reproducing the paper.
I have a question while reading the paper and looking at the code.
First of all, thank you for sharing the code.

Q1. In the paper 4.3 (IMAGE VERBALIZATION FOR EXPANSION), we need to obtain image verbalization results $V (I_j )$ to expend the raw captions passing through the text encoder.
>$C^*_j = C_j ; [SEP]; V (I_j )$　　(8)

However, I could not find a part that generates a potentially matching caption or related queries that corresponds to the image verbalization result.
I would appreciate it if you could tell me which part of the code corresponds to Image Verbalization.

Once again, thank you for revealing the code and I look forward to your reply.

**Comment by kiucho** [comment]
Hello, I found a breakthrough.

In folder `data` which I can download from [Ali Drive](https://thunlp.oss-cn-qingdao.aliyuncs.com/UniVLDR/data.zip),
There's `all_img_query.json` and `all_img_exp.json`.
I think `all_img_query.json` has generated **related query** and `all_img_exp.json` has generated **potentially matching caption**.

**Comment by EdwardZH** [comment]
Sure, you are right. We train VinVL to generate related queries according to image captions and image features.
