### ISSUE TITLE
Question about sum(caption embeddings, image embeddings)

### ISSUE THREAD

**Issue by wangqian621** [OpenMatch/UniVL-DR#4]
First of all, thank you for the code and paper~
I wonder  why caption embeddings and image embeddings can be added directly element by element？I have known that they are aligned by minimizing contrast loss in clip.
Thanks again!

**Comment by EdwardZH** [comment]
We have done some experiments to show this. I wonder it may derives in that both image and caption indicate the same  semantics and the embedding sum is usually used for semantic composition.
